blank_issues_enabled: false
contact_links:
  - name: Sự cố trên V2Ray
    url: https://github.com/v2fly/v2ray-core/
    about: Nếu bạn gặp vấn đề với V2Ray thay vì v2rayNG, vui lòng truy cập liên kết này để thảo luận.
